audit_header: false
title: St. George Mortgage Video Blog with Chantry Abbott
description: Our mission at -- CLIENT BRAND -- is to be your best resource for St. George Mortgage advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about Mortgage. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from Chantry Abbott.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Chantry Abbott
  title:
  license_number:
  about_markdown: |
    Chantry has been a residential loan officer since 2007. He specializes in educating and informing his clients about loan qualifying strategies, and choosing the best loan program for them. Chantry and his team can assist you buy a home, build a home, refinance your current mortgage, or obtain a reverse mortgage. Even if your not ready to apply for a loan today we would love to answer your questions, or help you make a strategy for the future
  brand:
  brokerage:
  market: St. George
  address: 1224 S. River Rd., Suite A102 & A200, St. George, UT 84790
  phone: 435-674-1090 ext. 105
  phone_type:
  phone2:
  phone2_type:
  email: chantry@simplifyingrealestate.tv
  url:

CTAs:
  first_CTA_text: Loan Application
  first_CTA_URL: https://myaccount.guildmortgage.com/officers/chantryabbott/apply-online/?v=2
  second_CTA_text: Contact
  second_CTA_URL: /contact/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Need a Home Loan?"
    CTA_text: Apply for a loan through Sponsor, Guild Mortgage
    CTA_link_text: "Apply Now"
    CTA_url: https://myaccount.guildmortgage.com/guild-home/apply-online/sign-up/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Get in Touch"
    CTA_text2: "Have questions or need to get in touch with us?"
    CTA_link_text2: "Contact Us"
    CTA_url2: /contact/

lender:
  show_section: true
  header_text: The Simplifying Real Estate Show is sponsored by Guild Mortgage
  headshot_path:
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'St. George Mortgage Podcast with Chantry Abbott'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for home loans in the St. George Area'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Chantry Abbott.'
  keywords: 'Real Estate for sale, Real Estate agents, top Mortgage agents, local Mortgage agents, find a Mortgage agent, houses for sale in St. George, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, Mortgage, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Chantry Abbott'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 30
  hero_text: St. George Mortgage Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#262a82'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#262a82'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
